# Generated by Django 4.2.7 on 2023-11-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_addres_teacher_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='addres',
        ),
    ]
