# Generated by Django 4.2.7 on 2023-11-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_address_teacher_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='addres',
            new_name='address',
        ),
    ]
